"""Purpose notes for scripts/envdoc.py — one line per variable, written from the code that reads it.

Keep each note true to the reading site (grep the file in the table before editing).
A variable missing here still appears in the generated table with purpose "—".
"""

NOTES = {
    # models
    "AWS_REGION": "Bedrock region — text model and Nova Sonic.",
    "OPENAI_API_KEY": "OpenAI Realtime key for the voice persona.",
    "GEMINI_API_KEY": "Gemini Live key; `GOOGLE_API_KEY` is the fallback.",
    "GOOGLE_API_KEY": "Fallback for `GEMINI_API_KEY`.",
    "TINY_MODEL_ID": "Bedrock model id for text personas.",
    # voice
    "VOICE_PROVIDER": "`openai` · `nova_sonic` · `gemini` — the bidi model.",
    "VOICE_NAME": "Provider voice; the robot sets `shimmer`.",
    "VOICE_MODEL": "OpenAI Realtime model override (robot: `gpt-realtime-2`).",
    "VOICE_LANG": "ISO-639-1 transcription hint (`tr`, `en`).",
    "VOICE_VAD_THRESHOLD": "Server-VAD threshold 0–1; higher = harder barge-in.",
    "VOICE_TURN_DETECTION": "`server_vad` or `semantic_vad`.",
    "VOICE_VAD_EAGERNESS": "`semantic_vad` turn-taking: `low`|`medium`|`high`|`auto`.",
    "VOICE_XMOS_PARAMS": "XVF3800 params written at start; `PP_NLATTENONOFF=0` = barge-in.",
    "REACHY_DAEMON_PYTHON": "Daemon venv interpreter for the USB audio fallback.",
    "VOICE_TRANSCRIBE_PROMPT": "Free-text hint for the transcriber.",
    "VOICE_VAD_SILENCE_MS": "Silence that ends a turn, ms.",
    "VOICE_VAD_PREFIX_MS": "Audio kept before speech onset, ms.",
    "TINY_PHOTO_QUESTION": "Default question `take_photo` asks the model.",
    "VOICE_RESTART_DELAY": "Seconds before rebuilding the session; doubles per fatal error.",
    "VOICE_RESTART_DELAY_MAX": "Cap for that backoff.",
    "VOICE_RELEASE_MEDIA": "`1` releases daemon media before each start (Lite).",
    "REACHY_AUDIO_RATE": "PyAudio device rate; resampled to the model.",
    # robot / SDK
    "REACHY_HOST": "Daemon host for SDK client and dashboard.",
    "REACHY_PORT": "Daemon HTTP port.",
    "REACHY_CONNECTION_MODE": "`auto` · `localhost_only` · `network` → `ReachyMini(connection_mode=)`.",
    "REACHY_MEDIA_BACKEND": "Shared client's media backend; `no_media` leaves it to the daemon.",
    "REACHY_CAMERA_BACKEND": "Backend for transient `reachy_camera` grabs.",
    "REACHY_USE_SIM": "`1` = MuJoCo simulation (`make sim`).",
    "REACHY_SPAWN_DAEMON": "`1` = SDK spawns a daemon if none answers.",
    "TINY_CAMERA_SNAPSHOT": "Where `reachy_camera` writes its frame.",
    "TINY_DASHBOARD_URL": "Dashboard URL the tools call for snapshots and holds.",
    "TINY_DASHBOARD_TOKEN": "Bearer for those calls off loopback.",
    "TINY_TTS_URL": "Piper TTS (`tiny-tts.service`) behind `reachy_say`.",
    "TINY_TTS_SPACE": "Legacy HF Space fallback (answers 401 today).",
    "TINY_TTS_REF_AUDIO": "Reference clip for that Space fallback.",
    # telegram
    "TELEGRAM_BOT_TOKEN": "Bot token for the telegram persona and tool.",
    "TELEGRAM_ALLOWED_USERS": "Usernames/ids allowed to talk (`(any)` = everyone).",
    "TELEGRAM_DEFAULT_CHAT_ID": "Chat for unsolicited messages (thinker notes, photos).",
    "TELEGRAM_HISTORY_LIMIT": "Recent messages injected per chat.",
    # thinker
    "THINKER_INTERVAL": "Seconds between thinker cycles (robot: 30).",
    "THINKER_DISABLED": "`1` makes the thinker a no-op.",
    # perception
    "REACHY_BOOT_VOLUME_MIN": "Minimum volume tiny-wake enforces — alsa-state can boot deaf.",
    "REACHY_FACE_TRACKING": "Legacy; see `REACHY_TRACK_AUTOSTART`.",
    "REACHY_TRACK_AUTOSTART": "`1` starts face tracking at boot and after daemon restarts.",
    "REACHY_TRACK_POLL_HZ": "Poll rate of the daemon's tracked face.",
    "REACHY_TRACK_REASSERT_MISSES": "`ts: null` polls before the tracker is re-enabled.",
    # daemon link (dashboard/daemonlink.py) — the EMFILE incident of 2026-09-17
    "REACHY_DAEMON_STREAM_HZ": "Rate asked of `/api/state/ws/full`.",
    "REACHY_DAEMON_STREAM_STALE_S": "Stream age that triggers one REST fallback read.",
    "REACHY_DAEMON_FALLBACK_HZ": "Cap on REST polls while the stream is down.",
    "REACHY_MOVES_IDLE_PROBE_S": "`/api/move/running` probe interval when idle.",
    "REACHY_MOVES_ACTIVE_HZ": "`/api/move/running` probe rate after a move.",
    "REACHY_FD_WARN_FRACTION": "Warn when daemon fds exceed this fraction.",
    "REACHY_CLOSE_WAIT_WARN": "Warn at this many CLOSE-WAIT sockets (incident: 614).",
    # turn toward the speaker (dashboard/doa.py)
    "REACHY_DOA_TURN": "`1` turns toward speech when no face is locked.",
    "REACHY_DOA_SIGN": "`1` (owner-confirmed) or `-1` if it turns away.",
    "REACHY_DOA_FRAME": "`head` (relative to head yaw) or `body` (absolute).",
    "REACHY_DOA_MIN_CONSEC": "Agreeing speech frames before a turn.",
    "REACHY_DOA_TOL_DEG": "How much those frames may disagree.",
    "REACHY_DOA_RATE_S": "Minimum seconds between DoA turns.",
    "REACHY_DOA_MIN_DELTA_DEG": "Bearings closer to straight ahead are ignored.",
    "REACHY_DOA_HEAD_MAX_DEG": "Head yaw before the body takes over.",
    "REACHY_DOA_BODY_MAX_DEG": "Body yaw a turn may reach.",
    "REACHY_DOA_RAIL_DEG": "Within this of 0/π = rail, ignored.",
    "REACHY_DOA_SPEAK_TAIL_S": "Seconds after speaking that speech still counts as own.",
    "REACHY_DOA_WINDUP_S": "Same-direction turns within this window need a shrinking bearing.",
    "REACHY_DOA_WINDUP_RATIO": "“Did not shrink” = new |delta| ≥ this × previous.",
    "REACHY_DOA_FACE_FRESH_S": "A face younger than this blocks DoA.",
    "REACHY_DOA_TURN_DURATION_S": "Duration of the DoA goto.",
    "REACHY_TRACK_HOLD_TTL": "Seconds before an unreleased tracking hold expires.",
    "REACHY_SPEAK_TAIL_S": "Extra seconds the `speaking` hold outlives audio.",
    # dashboard
    "REACHY_HTTP_PORT": "Dashboard port (behind the Cloudflare tunnel).",
    "REACHY_DAEMON_URL": "Daemon base URL for the dashboard.",
    "REACHY_DIST": "Built frontend directory (SPA shell).",
    "REACHY_LOG": "Dashboard log level.",
    "REACHY_WS_HZ": "State frames per second on `/ws`.",
    "REACHY_STATE_CACHE_S": "Coalesces `/api/state` reads — one daemon request per window.",
    "REACHY_RATE_LIMIT": "Control POSTs per second before 429.",
    "REACHY_ASK_TIMEOUT": "Seconds an Ask turn may run.",
    "REACHY_ASK_PREWARM": "`0` skips building the Ask agent at startup.",
    "REACHY_DASH_CAMERA": "`ipc` (coexists with tracking) · `rpicam` · `cv2`.",
    "REACHY_DASH_CAMERA_INDEX": "V4L2 index for `cv2`.",
    "REACHY_DASH_CAM_FPS": "MJPEG frame-rate cap.",
    "REACHY_DASH_CAMERA_OFF": "Any value disables the dashboard camera.",
    "REACHY_DASH_TTS_URL": "TTS for dashboard Say (defaults to `TINY_TTS_URL`).",
    "REACHY_CAMERA_SOCKET": "Daemon camera IPC socket path.",
    "REACHY_MEM_DB": "SQLite brain for the mind feed.",
    "REACHY_NO_AUTOAPP": "Tests: import `dashboard.server` without building the app.",
    # auth
    "REACHY_TOKEN": "Owner bearer — full `/api/*` and `/ws` (`Bearer` or `?token=`).",
    "REACHY_REG_TOKEN": "Required to enrol passkeys after the first (TOFU).",
    "REACHY_RP_ID": "WebAuthn relying-party id — the public hostname.",
    "REACHY_RP_NAME": "Display name in the passkey prompt.",
    "REACHY_ORIGIN": "Expected WebAuthn origin(s), comma-separated.",
    "REACHY_AUTH_STORE": "Passkey credential store path.",
    "REACHY_SESSION_STORE": "Session cookie store path.",
    "REACHY_SESSION_TTL": "Passkey session lifetime, seconds.",
    "REACHY_USER_NAME": "User handle the passkeys register under.",
    "REACHY_LOOPBACK_READS": "`0` disables keyless reads from the robot itself.",
    # fleet
    "TINY_MCP": "`1` mounts tiny.technology fleet tools (tiny-tech MCP).",
    "TINY_MCP_PERSONAS": "Personas that get fleet tools.",
    "TINY_TOKEN": "tiny.technology CLI JWT (`TINY_TOKEN_FILE` wins).",
    "TINY_TOKEN_FILE": "Mode-600 file holding that token. Never logged.",
    "TINY_MCP_HOME": "Isolated `TINY_HOME` for the MCP process.",
    "TINY_MCP_NODE": "node binary if not on PATH.",
    "TINY_MCP_TINY_TECH": "Path to a tiny-tech package dir.",
    "TINY_MCP_COMMAND": "Full server command, overriding auto-detect.",
    "TINY_MCP_MESH": "`1` joins the zenoh mesh (off: CPU).",
    "TINY_MCP_STARTUP_TIMEOUT": "Seconds to wait for the MCP handshake.",
    "TINY_MCP_TIMEOUT": "Per-call timeout for fleet tools.",
    "TINY_SELF_DEVICE_IDS": "This robot's device ids — `use_device` refuses itself.",
    "TINY_SELF_NAME": "Name prefixed to fleet prompts.",
}

GROUPS = {
    "REACHY_TOKEN": "Auth", "REACHY_REG_TOKEN": "Auth", "REACHY_RP_ID": "Auth", "REACHY_RP_NAME": "Auth",
    "REACHY_ORIGIN": "Auth", "REACHY_AUTH_STORE": "Auth", "REACHY_SESSION_STORE": "Auth",
    "REACHY_SESSION_TTL": "Auth", "REACHY_USER_NAME": "Auth", "REACHY_LOOPBACK_READS": "Auth",
    "REACHY_HTTP_PORT": "Dashboard", "REACHY_DAEMON_URL": "Dashboard", "REACHY_DIST": "Dashboard",
    "REACHY_LOG": "Dashboard", "REACHY_WS_HZ": "Dashboard", "REACHY_STATE_CACHE_S": "Dashboard",
    "REACHY_RATE_LIMIT": "Dashboard", "REACHY_ASK_TIMEOUT": "Dashboard", "REACHY_ASK_PREWARM": "Dashboard",
    "REACHY_CAMERA_SOCKET": "Dashboard", "REACHY_MEM_DB": "Dashboard", "REACHY_NO_AUTOAPP": "Dashboard",
    "REACHY_SPEAK_TAIL_S": "Perception", "REACHY_AUDIO_RATE": "Voice",
    "VOICE_LANG": "Voice", "VOICE_VAD_THRESHOLD": "Voice", "VOICE_TURN_DETECTION": "Voice", "VOICE_VAD_EAGERNESS": "Voice", "VOICE_TRANSCRIBE_PROMPT": "Voice", "VOICE_XMOS_PARAMS": "Voice", "REACHY_DAEMON_PYTHON": "Voice", "VOICE_VAD_SILENCE_MS": "Voice", "VOICE_VAD_PREFIX_MS": "Voice",
    "TINY_PHOTO_QUESTION": "Voice",
    "TINY_TTS_URL": "Robot", "TINY_TTS_SPACE": "Robot", "TINY_TTS_REF_AUDIO": "Robot",
    "TINY_CAMERA_SNAPSHOT": "Robot", "TINY_DASHBOARD_URL": "Robot", "TINY_DASHBOARD_TOKEN": "Robot",
    "TINY_MODEL_ID": "Models",
}
