"""Purpose notes for scripts/envdoc.py — one line per variable, written from the code that reads it.

Keep each note true to the reading site (grep the file in the table before editing).
A variable missing here still appears in the generated table with purpose "—".
"""

NOTES = {
    # models
    "AWS_REGION": "Bedrock region for the text model (tiny.py) and Nova Sonic voice.",
    "OPENAI_API_KEY": "OpenAI Realtime key for the voice persona (`VOICE_PROVIDER=openai`).",
    "GEMINI_API_KEY": "Gemini Live key (`VOICE_PROVIDER=gemini`); `GOOGLE_API_KEY` is the fallback name.",
    "GOOGLE_API_KEY": "Fallback for `GEMINI_API_KEY`.",
    "TINY_MODEL_ID": "Bedrock model id for the text personas.",
    # voice
    "VOICE_PROVIDER": "`openai` (Realtime) · `nova_sonic` · `gemini` — which bidi model voice_listener builds.",
    "VOICE_NAME": "Provider voice; code default alloy/tiffany/Kore, the robot sets `shimmer`.",
    "VOICE_MODEL": "OpenAI Realtime model override (robot: `gpt-realtime-2`); unset = strands' default.",
    "VOICE_LANG": "ISO-639-1 transcription hint (`tr`, `en`); unset auto-detects phantom languages.",
    "VOICE_VAD_THRESHOLD": "Server-VAD speech threshold 0–1; higher makes barge-in harder.",
    "VOICE_TURN_DETECTION": "`server_vad` or `semantic_vad` — how OpenAI decides your turn ended.",
    "VOICE_VAD_EAGERNESS": "`semantic_vad` only: `low` | `medium` | `high` | `auto` turn-taking speed.",
    "VOICE_XMOS_PARAMS": "XVF3800 params written at every start; `PP_NLATTENONOFF=0` enables barge-in.",
    "REACHY_DAEMON_PYTHON": "Pollen's daemon venv interpreter, for the USB audio-param fallback.",
    "VOICE_TRANSCRIBE_PROMPT": "Free-text hint for the transcriber (`Turkish or English, talking to TINY`).",
    "VOICE_VAD_SILENCE_MS": "Silence that ends a user turn, ms (default 600).",
    "VOICE_VAD_PREFIX_MS": "Audio kept before detected speech onset, ms (default 300).",
    "TINY_PHOTO_QUESTION": "What `take_photo` asks the voice model when no question is given.",
    "VOICE_RESTART_DELAY": "Seconds before rebuilding the voice session; doubles per fatal error.",
    "VOICE_RESTART_DELAY_MAX": "Cap for that backoff — a bad key retries every 5 min.",
    "VOICE_RELEASE_MEDIA": "1 = release daemon media before each voice start (Lite only).",
    "REACHY_AUDIO_RATE": "PyAudio device rate; resampled to the model's 24 kHz / 16 kHz.",
    # robot / SDK
    "REACHY_HOST": "Daemon host for the SDK client and the dashboard.",
    "REACHY_PORT": "Daemon HTTP port (Pollen daemon listens on :8000).",
    "REACHY_CONNECTION_MODE": "`auto` · `localhost_only` · `network` — passed to `ReachyMini(connection_mode=)`. The robot runs `localhost_only`.",
    "REACHY_MEDIA_BACKEND": "Shared client's SDK media backend; `no_media` leaves media to the daemon.",
    "REACHY_CAMERA_BACKEND": "Media backend for `reachy_camera` / `reachy_look_at` transient frame grabs.",
    "REACHY_USE_SIM": "`1` = the MuJoCo simulation instead of the robot (`make sim`).",
    "REACHY_SPAWN_DAEMON": "`1` = let the SDK spawn a daemon if none answers.",
    "TINY_CAMERA_SNAPSHOT": "Where `reachy_camera` writes the frame it hands to the vision model.",
    "TINY_DASHBOARD_URL": "Dashboard base URL the tools call for snapshots and tracking holds.",
    "TINY_DASHBOARD_TOKEN": "Bearer for those calls off loopback (falls back to `REACHY_TOKEN`).",
    "TINY_TTS_URL": "Piper TTS (`tiny-tts.service`, 127.0.0.1:5002) behind `reachy_say` and dashboard Say.",
    "TINY_TTS_SPACE": "Legacy Hugging Face Space fallback for `reachy_say` (answers 401 today).",
    "TINY_TTS_REF_AUDIO": "Reference voice clip for that Space fallback.",
    # telegram
    "TELEGRAM_BOT_TOKEN": "Bot token for the telegram persona and the `telegram` tool.",
    "TELEGRAM_ALLOWED_USERS": "Comma-separated usernames/ids allowed to talk to TINY (`(any)` = everyone).",
    "TELEGRAM_DEFAULT_CHAT_ID": "Chat that receives unsolicited messages (thinker notes, photos).",
    "TELEGRAM_HISTORY_LIMIT": "Recent messages injected per chat as context (default 20).",
    # thinker
    "THINKER_INTERVAL": "Seconds between thinker cycles (robot: 30).",
    "THINKER_DISABLED": "`1` makes the thinker loop a no-op.",
    # perception
    "REACHY_BOOT_VOLUME_MIN": "Minimum speaker volume tiny-wake enforces at boot — alsa-state can boot deaf.",
    "REACHY_FACE_TRACKING": "Legacy `1` = face tracker at dashboard boot; see `REACHY_TRACK_AUTOSTART`.",
    "REACHY_TRACK_AUTOSTART": "`1` (default) starts face tracking at boot and after daemon restarts.",
    "REACHY_TRACK_POLL_HZ": "Dashboard poll rate of the daemon's tracked face (default 2 Hz).",
    "REACHY_TRACK_REASSERT_MISSES": "Consecutive `ts: null` face polls before the dashboard re-enables the tracker.",
    # daemon link (dashboard/daemonlink.py) — the EMFILE incident of 2026-09-17
    "REACHY_DAEMON_STREAM_HZ": "Rate asked of `/api/state/ws/full`, the single state source.",
    "REACHY_DAEMON_STREAM_STALE_S": "A stream frame older than this triggers one REST fallback read.",
    "REACHY_DAEMON_FALLBACK_HZ": "Cap on REST `/api/state/full` polls while the stream is down.",
    "REACHY_MOVES_IDLE_PROBE_S": "Seconds between `/api/move/running` probes when nothing is in flight.",
    "REACHY_MOVES_ACTIVE_HZ": "`/api/move/running` probe rate right after a dashboard move.",
    "REACHY_FD_WARN_FRACTION": "Warn when daemon open fds exceed this fraction of its limit.",
    "REACHY_CLOSE_WAIT_WARN": "Warn at this many CLOSE-WAIT sockets on :8000 (the incident: 614).",
    # turn toward the speaker (dashboard/doa.py)
    "REACHY_DOA_TURN": "`1` (default) turns toward speech when face tracking has no lock.",
    "REACHY_DOA_SIGN": "`1` (owner-confirmed) or `-1` if the head turns away from speakers.",
    "REACHY_DOA_FRAME": "`head` (bearing relative to head yaw) or `body` (absolute).",
    "REACHY_DOA_MIN_CONSEC": "Consecutive agreeing speech frames (10 Hz) before a turn.",
    "REACHY_DOA_TOL_DEG": "How much those frames may disagree (default ±12°).",
    "REACHY_DOA_RATE_S": "Minimum seconds between DoA turns (default 3).",
    "REACHY_DOA_MIN_DELTA_DEG": "Bearings closer than this to straight ahead are ignored.",
    "REACHY_DOA_HEAD_MAX_DEG": "Head yaw a DoA turn may use before the body takes over.",
    "REACHY_DOA_BODY_MAX_DEG": "Body yaw a DoA turn may reach (default ±60°).",
    "REACHY_DOA_RAIL_DEG": "Bearings within this of 0/π are the array's rails — ignored.",
    "REACHY_DOA_SPEAK_TAIL_S": "Seconds after TINY stops speaking that speech still counts as its own.",
    "REACHY_DOA_WINDUP_S": "Same-direction turns within this window without a shrinking bearing are refused.",
    "REACHY_DOA_WINDUP_RATIO": "“Did not shrink” = new |delta| ≥ this × the previous one.",
    "REACHY_DOA_FACE_FRESH_S": "A tracked face younger than this blocks DoA turns.",
    "REACHY_DOA_TURN_DURATION_S": "Duration of the DoA goto (default 0.7 s).",
    "REACHY_TRACK_HOLD_TTL": "Seconds after which an unreleased tracking hold (speaking/emotion/look) expires.",
    "REACHY_SPEAK_TAIL_S": "Extra seconds the `speaking` hold outlives the last audio chunk.",
    # dashboard
    "REACHY_HTTP_PORT": "Dashboard listen port (8097, fronted by the Cloudflare tunnel).",
    "REACHY_DAEMON_URL": "Daemon base URL the dashboard talks to.",
    "REACHY_DIST": "Built frontend directory served as the SPA shell.",
    "REACHY_LOG": "Dashboard log level.",
    "REACHY_WS_HZ": "State frames per second pushed on `/ws`.",
    "REACHY_STATE_CACHE_S": "Coalesces `/api/state` reads — many viewers, one daemon request per window.",
    "REACHY_RATE_LIMIT": "Control POSTs per second per client before 429.",
    "REACHY_ASK_TIMEOUT": "Seconds a dashboard Ask turn may run.",
    "REACHY_ASK_PREWARM": "`0` skips building the Ask agent at startup.",
    "REACHY_DASH_CAMERA": "`ipc` (default; coexists with face tracking) · `rpicam` · `cv2`.",
    "REACHY_DASH_CAMERA_INDEX": "V4L2 index for the `cv2` backend.",
    "REACHY_DASH_CAM_FPS": "MJPEG frame-rate cap.",
    "REACHY_DASH_CAMERA_OFF": "Any value disables the dashboard camera entirely.",
    "REACHY_DASH_TTS_URL": "TTS endpoint for the dashboard Say (defaults to `TINY_TTS_URL`).",
    "REACHY_CAMERA_SOCKET": "Path of the daemon's camera IPC socket.",
    "REACHY_MEM_DB": "SQLite brain the dashboard reads for the mind feed.",
    "REACHY_NO_AUTOAPP": "Set in tests so importing `dashboard.server` does not build the app.",
    # auth
    "REACHY_TOKEN": "Owner bearer token — full `/api/*` and `/ws` access (`Bearer` or `?token=`).",
    "REACHY_REG_TOKEN": "Registration token required to enrol additional passkeys after the first (TOFU).",
    "REACHY_RP_ID": "WebAuthn relying-party id — the cockpit's public hostname.",
    "REACHY_RP_NAME": "Display name shown by the passkey prompt.",
    "REACHY_ORIGIN": "Expected WebAuthn origin(s), comma-separated (default `https://<RP_ID>`).",
    "REACHY_AUTH_STORE": "Passkey credential store path.",
    "REACHY_SESSION_STORE": "Session cookie store path (next to the credential store).",
    "REACHY_SESSION_TTL": "Passkey session lifetime in seconds (12 h).",
    "REACHY_USER_NAME": "User handle the passkeys are registered under.",
    "REACHY_LOOPBACK_READS": "`0` disables keyless reads from the robot's own processes.",
    # fleet
    "TINY_MCP": "`1` mounts the tiny.technology fleet tools via the tiny-tech MCP server.",
    "TINY_MCP_PERSONAS": "Personas that get fleet tools (robot: `telegram,dashboard,shell,voice`).",
    "TINY_TOKEN": "tiny.technology CLI JWT for the MCP server (`TINY_TOKEN_FILE` wins).",
    "TINY_TOKEN_FILE": "Mode-600 file holding that token. Never logged.",
    "TINY_MCP_HOME": "Isolated `TINY_HOME` for the MCP server process.",
    "TINY_MCP_NODE": "Path to the node binary if not on PATH.",
    "TINY_MCP_TINY_TECH": "Path to a tiny-tech package dir (`…/node_modules/tiny-tech`).",
    "TINY_MCP_COMMAND": "Full command to run the server instead of the auto-detected one.",
    "TINY_MCP_MESH": "`1` joins the zenoh mesh (off: CPU on the CM4).",
    "TINY_MCP_STARTUP_TIMEOUT": "Seconds to wait for the MCP handshake before starting without fleet tools.",
    "TINY_MCP_TIMEOUT": "Per-call timeout for fleet tools.",
    "TINY_SELF_DEVICE_IDS": "This robot's tiny.technology device ids — `use_device` refuses to invoke itself.",
    "TINY_SELF_NAME": "Name prefixed to fleet prompts: `[fleet depth=1 from <name>]`.",
}

GROUPS = {
    "REACHY_TOKEN": "Auth", "REACHY_REG_TOKEN": "Auth", "REACHY_RP_ID": "Auth", "REACHY_RP_NAME": "Auth",
    "REACHY_ORIGIN": "Auth", "REACHY_AUTH_STORE": "Auth", "REACHY_SESSION_STORE": "Auth",
    "REACHY_SESSION_TTL": "Auth", "REACHY_USER_NAME": "Auth", "REACHY_LOOPBACK_READS": "Auth",
    "REACHY_HTTP_PORT": "Dashboard", "REACHY_DAEMON_URL": "Dashboard", "REACHY_DIST": "Dashboard",
    "REACHY_LOG": "Dashboard", "REACHY_WS_HZ": "Dashboard", "REACHY_STATE_CACHE_S": "Dashboard",
    "REACHY_RATE_LIMIT": "Dashboard", "REACHY_ASK_TIMEOUT": "Dashboard", "REACHY_ASK_PREWARM": "Dashboard",
    "REACHY_CAMERA_SOCKET": "Dashboard", "REACHY_MEM_DB": "Dashboard", "REACHY_NO_AUTOAPP": "Dashboard",
    "REACHY_SPEAK_TAIL_S": "Perception", "REACHY_AUDIO_RATE": "Voice",
    "VOICE_LANG": "Voice", "VOICE_VAD_THRESHOLD": "Voice", "VOICE_TURN_DETECTION": "Voice", "VOICE_VAD_EAGERNESS": "Voice", "VOICE_TRANSCRIBE_PROMPT": "Voice", "VOICE_XMOS_PARAMS": "Voice", "REACHY_DAEMON_PYTHON": "Voice", "VOICE_VAD_SILENCE_MS": "Voice", "VOICE_VAD_PREFIX_MS": "Voice",
    "TINY_PHOTO_QUESTION": "Voice",
    "TINY_TTS_URL": "Robot", "TINY_TTS_SPACE": "Robot", "TINY_TTS_REF_AUDIO": "Robot",
    "TINY_CAMERA_SNAPSHOT": "Robot", "TINY_DASHBOARD_URL": "Robot", "TINY_DASHBOARD_TOKEN": "Robot",
    "TINY_MODEL_ID": "Models",
}
