"""One-line descriptions for scripts/routedoc.py, keyed "METHOD /path" — written from the handler code."""

NOTES = {
    "GET /api/health": "Liveness, daemon reachability, camera, fd pressure, stream status. Public.",
    "GET /api/doa": "Turn-toward-speaker status: enabled, last bearing, why not turning, counters.",
    "POST /api/doa": "`{enabled}` — turn toward speech without a face lock (`K`); loopback ok.",
    "GET /api/state": "Full robot state: pose, motors, daemon Hz, CM4 stats, services, tracking.",
    "GET /api/telemetry": "State + camera status — the tiny.technology endpoint-device `telemetry` action.",
    "GET /api/emotions": "The recorded-move library the daemon exposes (81 moves on 1.10).",
    "GET /api/log": "Tail of the cross-persona agent log (`n` ≤ 300, `after` = row id) + events.",
    "GET /api/ask/last": "Whether an Ask turn is running and the last answer.",
    "GET /api/stream": "MJPEG from the dashboard camera — one daemon client shared by every viewer.",
    "GET /api/snapshot.jpg": "Latest JPEG frame (503 while the camera has none).",
    "GET /api/camera/snapshot": "Alias of `/api/snapshot.jpg` — the endpoint-device `snapshot` action.",
    "POST /api/chat": "One fleet agent turn (depth-capped, no use_device); waits ≤ 75 s.",
    "POST /api/control/look": "Head pose in degrees/mm (clamped), optional `antennas`, `body_yaw`, `duration`.",
    "POST /api/control/antennas": "Antenna angles in degrees.",
    "POST /api/control/express": "Play a recorded move by `name`.",
    "POST /api/control/stop": "E-stop: cancel the running move.",
    "POST /api/control/home": "Neutral pose.",
    "POST /api/control/wake": "Wake the daemon (motors on, wake emote).",
    "POST /api/control/sleep": "Sleep pose, motors relaxed.",
    "POST /api/control/motors": "`mode`: enabled · disabled · gravity_compensation.",
    "POST /api/control/volume": "Speaker volume `level` 0–100 (→ daemon `/api/volume/set`).",
    "POST /api/control/say": "Piper TTS → daemon `play_sound` with head wobble; returns `{engine, seconds}`.",
    "POST /api/control/ask": "Dashboard Ask turn (persona `dashboard`, full tools) → `/ws` `agent_log` rows.",
    "POST /api/control/reel": "Start the showcase reel (`action: start`) or `abort` it.",
    "POST /api/control/demo": "Demo mode: `on: true` pauses tiny-thinker so manual moves are not overlapped.",
    "GET /api/tracking": "Face-tracking controller status: enabled, detected, x/y, holds, paused, engine `daemon-yunet`.",
    "POST /api/tracking": "Daemon face tracker on/off (`enabled`); loopback ok — the `head_tracking` tool.",
    "POST /api/tracking/hold": "Named hold (`name`, `on`, `ttl`) pausing tracking while TINY speaks or emotes.",
    "WS /ws": "State at `REACHY_WS_HZ` (15/s) + `agent_log` rows + events; anonymous → 4401.",
    "GET /": "The SPA shell (Cache-Control no-cache — Cloudflare edge-caches hashed assets, not index.html).",
    "GET /{path:path}": "Static assets / SPA fallback.",
    "GET /api/auth/status": "Who am I: passkey session, bearer or anonymous; is TOFU enrolment open.",
    "POST /api/auth/logout": "Drop the passkey session cookie.",
    "POST /api/auth/register/begin": "WebAuthn registration options (first passkey = TOFU; afterwards needs `REACHY_REG_TOKEN`).",
    "POST /api/auth/register/complete": "Store the new passkey.",
    "POST /api/auth/login/begin": "WebAuthn assertion options.",
    "POST /api/auth/login/complete": "Verify the assertion, set the session cookie (12 h).",
    "GET /api/auth/credentials": "List enrolled passkeys (owner only).",
    "DELETE /api/auth/credentials/{cid}": "Remove a passkey (owner only).",
}
