"""One-line descriptions for scripts/routedoc.py, keyed "METHOD /path" — written from the handler code."""

NOTES = {
    "GET /api/health": "Liveness, daemon, camera, fd pressure. Public.",
    "GET /api/doa": "Turn-toward-speaker status and why not.",
    "POST /api/doa": "`{enabled}` — turn toward speech (`K`); loopback ok.",
    "GET /api/state": "Full robot state: pose, motors, services, tracking.",
    "GET /api/telemetry": "State + camera — the endpoint-device `telemetry` action.",
    "GET /api/emotions": "The daemon's recorded-move library (81 on 1.10).",
    "GET /api/log": "Agent-log tail (`n` ≤ 300, `after` = row id).",
    "GET /api/ask/last": "Is an Ask running; the last answer.",
    "GET /api/stream": "MJPEG — one daemon client for every viewer.",
    "GET /api/snapshot.jpg": "Latest JPEG (503 while none).",
    "GET /api/camera/snapshot": "Alias — the endpoint-device `snapshot` action.",
    "POST /api/chat": "One fleet agent turn; waits ≤ 75 s.",
    "POST /api/control/look": "Head pose (clamped), optional `antennas`, `body_yaw`, `duration`.",
    "POST /api/control/antennas": "Antenna angles, degrees.",
    "POST /api/control/express": "Play a recorded move by `name`.",
    "POST /api/control/stop": "E-stop: cancel the running move.",
    "POST /api/control/home": "Neutral pose.",
    "POST /api/control/wake": "Motors on, wake emote.",
    "POST /api/control/sleep": "Sleep pose, motors relaxed.",
    "POST /api/control/motors": "`mode`: enabled · disabled · gravity_compensation.",
    "POST /api/control/volume": "Speaker `level` 0–100.",
    "POST /api/control/say": "Piper TTS with head wobble → `{engine, seconds}`.",
    "POST /api/control/ask": "Dashboard Ask turn → `/ws` `agent_log` rows.",
    "POST /api/control/reel": "Showcase reel: `start` or `abort`.",
    "POST /api/control/demo": "`on: true` pauses tiny-thinker.",
    "GET /api/tracking": "Face-tracking status: detected, x/y, holds, paused.",
    "POST /api/tracking": "Tracker on/off (`enabled`); loopback ok.",
    "POST /api/tracking/hold": "Named hold (`name`, `on`, `ttl`) while TINY speaks.",
    "WS /ws": "State at `REACHY_WS_HZ` + `agent_log` + events; anonymous → 4401.",
    "GET /": "The SPA shell (no-cache).",
    "GET /{path:path}": "Static assets / SPA fallback.",
    "GET /api/auth/status": "Who am I; is TOFU enrolment open.",
    "POST /api/auth/logout": "Drop the session cookie.",
    "POST /api/auth/register/begin": "WebAuthn registration options (TOFU, then `REACHY_REG_TOKEN`).",
    "POST /api/auth/register/complete": "Store the new passkey.",
    "POST /api/auth/login/begin": "WebAuthn assertion options.",
    "POST /api/auth/login/complete": "Verify, set the session cookie.",
    "GET /api/auth/credentials": "List passkeys (owner).",
    "DELETE /api/auth/credentials/{cid}": "Remove a passkey (owner).",
}
