"""One-line descriptions for scripts/routedoc.py, keyed "METHOD /path" — written from the handler code."""

NOTES = {
    "GET /api/health": "Liveness + daemon reachability, camera status, last error, daemon pressure (fds/limit, CLOSE-WAIT on :8000) and the state-stream status. The only public `/api/*` route.",
    "GET /api/doa": "Turn-toward-speaker controller status: enabled, last bearing (deg), why it is not turning, turns/windups, sign cross-check counters.",
    "POST /api/doa": "`{enabled: bool}` — turn toward speech when face tracking has no lock (default on; `K` in the cockpit). Personas may call it from 127.0.0.1 without a key.",
    "GET /api/state": "Full robot state: head/body/antenna pose, motor mode, daemon loop Hz, CM4 system stats, service states, tracking/doa/imu when present.",
    "GET /api/telemetry": "State + camera status — the tiny.technology endpoint-device `telemetry` action.",
    "GET /api/emotions": "The recorded-move library the daemon exposes (81 moves on 1.10).",
    "GET /api/log": "Tail of the cross-persona agent log (`n` ≤ 300 rows, `after` = row id) + recent dashboard events.",
    "GET /api/ask/last": "Whether an Ask turn is running and the last answer.",
    "GET /api/stream": "MJPEG stream from the dashboard camera (one daemon camera client shared by every viewer).",
    "GET /api/snapshot.jpg": "Latest JPEG frame (503 while the camera has none).",
    "GET /api/camera/snapshot": "Alias of `/api/snapshot.jpg` — the endpoint-device `snapshot` action.",
    "POST /api/chat": "One agent turn as a *fleet* turn (depth-capped, no use_device) — the endpoint-device `chat` action; waits up to 75 s.",
    "POST /api/control/look": "Head pose in degrees/mm (clamped in robot.py), optional `antennas: [right, left]`, `body_yaw`, `duration`.",
    "POST /api/control/antennas": "Antenna angles in degrees.",
    "POST /api/control/express": "Play a recorded move by `name`.",
    "POST /api/control/stop": "E-stop: cancel the running move.",
    "POST /api/control/home": "Neutral pose.",
    "POST /api/control/wake": "Wake the daemon (motors on, wake emote).",
    "POST /api/control/sleep": "Sleep pose, motors relaxed.",
    "POST /api/control/motors": "`mode`: enabled · disabled · gravity_compensation.",
    "POST /api/control/volume": "Speaker volume `level` 0–100 (→ daemon `/api/volume/set`).",
    "POST /api/control/say": "Piper TTS on the CM4 → daemon `play_sound` with head wobble; returns `{engine, seconds}`.",
    "POST /api/control/ask": "Run a dashboard Ask turn (persona `dashboard`, full tools); streams to `/ws` as `agent_log` rows.",
    "POST /api/control/reel": "Start the showcase reel (`action: start`) or `abort` it.",
    "POST /api/control/demo": "Demo mode: pause (`on: true`) / resume the tiny-thinker persona so manual moves are not overlapped.",
    "GET /api/tracking": "Face-tracking controller status: enabled, detected, x/y, holds, paused, engine `daemon-yunet`.",
    "POST /api/tracking": "Turn the daemon face tracker on/off (`enabled`). Also allowed from 127.0.0.1 without a key — the personas' `head_tracking` tool.",
    "POST /api/tracking/hold": "Named hold (`name`: speaking · emotion:<n> · look …, `on`, `ttl` s) that pauses tracking while TINY speaks or emotes.",
    "WS /ws": "State frames at `REACHY_WS_HZ` (15/s) + `agent_log` rows + events; anonymous sockets are closed with 4401.",
    "GET /": "The SPA shell (Cache-Control no-cache — Cloudflare edge-caches hashed assets, not index.html).",
    "GET /{path:path}": "Static assets / SPA fallback.",
    "GET /api/auth/status": "Who am I: passkey session, bearer, or anonymous; whether TOFU enrolment is open.",
    "POST /api/auth/logout": "Drop the passkey session cookie.",
    "POST /api/auth/register/begin": "WebAuthn registration options (first passkey = TOFU; afterwards needs `REACHY_REG_TOKEN`).",
    "POST /api/auth/register/complete": "Store the new passkey.",
    "POST /api/auth/login/begin": "WebAuthn assertion options.",
    "POST /api/auth/login/complete": "Verify the assertion, set the session cookie (12 h).",
    "GET /api/auth/credentials": "List enrolled passkeys (owner only).",
    "DELETE /api/auth/credentials/{cid}": "Remove a passkey (owner only).",
}
